config/routes.rb
Rails.application.routes.draw do
  
  

  get 'reviews/new'

  get 'reviews/create'

  get 'reviews/update'

  root 'static_pages#home'

  resources :listings do
    collection do
      get 'search'
    end
    resources :orders, only: [:show, :new, :create]
    resources :comments, only: [:create, :destroy]
  end
  
  resources :orders, only: [] do
    put "ship", on: :member
  end
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]  
  resources :bank_accounts, only: [:new, :create, :index, :destroy] do
    resources :transfers, only: [:new, :create]
  end
  
  resources :bank_accounts, only: [] do
    put "confirmar", on: :member
  end
  
  resources :transfers, only: [] do
    put "confirmar", on: :member
  end
  
  resources :transfers, only: [:index]
  
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'password_reset/new'

  get 'password_reset/edit'
  
  get 'sales', to: "orders#sales"
  get 'purchases', to: "orders#purchases"
  get 'seller', to: "listings#seller"
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'bank_accounts/monitoreo', to: 'bank_accounts#monitoreo'
  get 'orders/monitoreo'
  get 'transfers/monitoreo'
  
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  mount_uploader :picture, PictureUploader
  validates :name, :description, :price, :user_id, :category_id, :subcategory_id, presence: true
  validates_presence_of :picture
  validates :price, numericality: { greater_than: 0 }
  validate  :picture_size
  has_many :orders
  has_many :comments
  belongs_to :subcategory
  belongs_to :category
  
  has_one :pickup_address, as: :addressable, class_name: "Address", dependent: :destroy
  
  accepts_nested_attributes_for :pickup_address
  
  searchkick
  
  private
    
    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
  
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:new, :create, :destroy]
  before_action :correct_user,   only: [:destroy, :edit, :update]
  before_action :complete_user, only: [:new, :create]
  # GET /listings
  # GET /listings.json
  
  def search
    search = params[:search].presence || "*"
    conditions = {}
    conditions[:price] = params[:price] if params[:price].present?
    @listings = Listing.search search, where: conditions, aggs: [:price]
  end
  
  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC")
  end
  
  def index
    if params[:subcategory].blank?
      @listings = Listing.all.order("created_at DESC")
    else
      @subcategory_id = Subcategory.find_by(name: params[:subcategory]).id
      @listings = Listing.where(subcategory_id: @subcategory_id).order("created_at DESC")
    end
  end
  
  def get_subcategories
    @subcategories = Subcategory.where(category_id: params[:category_id])
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @comment = @listing.comments.build if logged_in?
  end

  # GET /listings/new
  def new
    @listing = current_user.listings.build
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = current_user.listings.build(listing_params)

    if @listing.save
      flash[:success] = "listing created!"
      redirect_to @listing
    else
      render 'new'
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end
    

    def correct_user
      unless current_user?(@listing.user)
        redirect_to(root_url)
        flash[:danger] = "Sorry, this listing belongs to someone else"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :picture, 
                                          :subcategory_id, :category_id,
                                          pickup_address_attributes: [:city, :sector,
                                                            :line_1, :line_2])
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_comment_form.html.erb
<%= form_for ([@listing, @comment]) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    
    <%= f.text_area :content, class: 'form-control' %>
    <%= f.submit "comentar", class: "btn btn-primary" %>
<% end %>

app/views/listings/_form.html.erb
<%= form_for(setup_listing(@listing), html: { multipart: true }) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
<div class = "row">
      <div class = "col-md-6 col-md-offset-3">

    <%= f.label :name, "Nombre del Producto" %>
    <%= f.text_field :name, class: 'form-control' %>
    
    
    <%= label_tag nil, "Categoria" %>
    <div class = "row">
      
      <div class= "col-md-6">
        <%= f.collection_select(:category_id, Category.all, :id, :name, 
                      { prompt: 'Elige una categoria' }, { id: 'category-select', class: 'form-control' }) %>
      </div>
      
                      
      <div class= "col-md-6">
        <%= f.grouped_collection_select :subcategory_id, Category.all, :subcategories, 
            :name, :id, :name, { include_blank: 'Elige una sub categoria' }, { id: 'subcategory-select', class: 'form-control' } %>
      </div>
      
    </div>
    
    <%= f.label :description, "Descripción" %>
    <%= f.text_area :description, class: 'form-control' %>

    <%= f.label :price, "Precio" %>
    <%= f.text_field :price, class: 'form-control' %>
    
    <%= f.fields_for :pickup_address do |u| %>
        
        <%= u.label :city, "Ciudad" %>
        <%= u.text_field :city, class: 'form-control' %>
        
        <!--%= u.label :sector %-->
        <!--%= u.text_field :sector, class: 'form-control' %>
        
        <!--%= u.label :line_1, "calle" %>
        <!--%= u.text_field :line_1, class: 'form-control' %>
        
        <!--%= u.label :line_2, "Numero de casa/Apt o residencial" %>
        <!--%= u.text_field :line_2, class: 'form-control' %-->
        
    <% end %>

  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', class: 'form-control' %>
  </span>

    <%= f.submit "Publicar Anuncio", class: "btn btn-primary" %>
 </div>
 </div>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/listings/_thumbnail.html.erb
    
  
    <% @listings.each do |listing| %>
      <div class="col-md-4">
        <div class="thumbnail">
          <%= link_to image_tag(listing.picture.url), listing %>
          <div class="caption">
            <h3><%= listing.name %></h3>
            <p><%= number_to_currency(listing.price) %></p>
            <p><%= "Vendido por #{listing.user.name}" %></p>
          </div>
        </div>
      </div>
    <% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
  <div class="row center">
    <% if current_user.present? %>
      <%= render 'layouts/sidebar' %>
      <div class ="col-md-9">
    <% else %>
    <div class ="col-md-12">
    <% end %>
    <%= render 'listings/thumbnail' %>
  </div>
</div> 
  
<%= link_to "Publicar Anuncio", new_listing_path, class: "btn btn-primary" if current_user.present?%>

app/views/listings/new.html.erb
<h1>Crear anuncio</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'regreso', listings_path %>

app/views/listings/search.html.erb
<div class="row center">
    <% if current_user.present? %>
      <%= render 'layouts/sidebar' %>
      <div class ="col-md-9">
    <% else %>
    <div class ="col-md-12">
    <% end %>
    <%= render 'listings/thumbnail' %>
  </div>
</div> 
<!--% @listings.aggs.each do |ags|%>
        <span>ags</span>
        <ul  class="menu">
        <!--% @listings.aggs["price"]["buckets"].each do |filter| %>
          <li><!--%= link_to "#{filter["key"]} (#{filter["doc_count"]})", "/listings/search?price=#{filter["key"]}" %></li>
        <!--% end %>
        </ul>
    <!--% end %-->
  
<%= link_to "Publicar Anuncio", new_listing_path, class: "btn btn-primary" if current_user.present?%>

app/views/listings/seller.html.erb
<table class="table table-striped">
  <tr>
    <th class="center">Image</th>
    <th class="center">Name</th>
    <th class="center">Description</th>
    <th class="center">Price</th>
    <th class="center">Action</th>
  </tr>

  <% @listings.each do |listing| %>
    <tr>
      <td class="center"><%= image_tag listing.picture.url(:thumb) %></td>
      <td class="center"><%= listing.name %></td>
      <td class="center"><%= listing.description %></td>
      <td class="center"><%= number_to_currency(listing.price) %></td>
      <td>
        <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "View", listing, class: "btn btn-link" %></li>
            <li><%= link_to "Edit", edit_listing_path(listing), class: "btn btn-link" %></li>
            <li><%= link_to 'Destroy', listing, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-link" %></li>
          </ul>
        </div>
      </td>
    </tr>
  <% end %>
</table>

app/views/listings/show.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="thumbnail">
      <%= image_tag @listing.picture.url %>
    </div>
  </div>
  <div class="col-md-4 col-md-offset-2">
    <h3><%= @listing.name %></h3>
    <p><%= number_to_currency(@listing.price) %></p>
    <p><%= @listing.description %></p>
    <br>
    <p>Ciudad: <%= @listing.pickup_address.city %></p>
    <p>Telefono: <%= @listing.user.telefono %></p>
    <!--div class="center"-->
      <!--%= link_to "Buy It Now", new_listing_order_path(@listing), class: "btn btn-primary", data:  { turbolinks: false } %>
    </div-->
      
  </div>
</div>
<% if current_user?(@listing.user)%>
  <%= link_to 'Editar', edit_listing_path(@listing), class: "btn btn-link" %>
<% end %>
<%= link_to 'Atras', listings_path, class: "btn btn-link" %>
<br>

  <div class="row">
    <div class="col-md-8 col-md-offset-4">
        <% if @listing.comments.any? %>
          <div class="box">
            <%= render @listing.comments %>
          </div>
        <%end%>
        
        <% if logged_in? %>
          <%= render 'listings/comment_form' %>
        <% else %>
          <%= link_to "Inicia sesion para esribir un comentario", login_path, class: "btn btn-primary col-md-offset-4" %>
        <% end %>
    </div>
  </div>