config/routes.rb
Rails.application.routes.draw do
  
  

  get 'reviews/new'

  get 'reviews/create'

  get 'reviews/update'

  root 'static_pages#home'

  resources :listings do
    collection do
      get 'search'
    end
    resources :orders, only: [:show, :new, :create]
    resources :comments, only: [:create, :destroy]
  end
  
  resources :orders, only: [] do
    put "ship", on: :member
  end
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]  
  resources :bank_accounts, only: [:new, :create, :index, :destroy] do
    resources :transfers, only: [:new, :create]
  end
  
  resources :bank_accounts, only: [] do
    put "confirmar", on: :member
  end
  
  resources :transfers, only: [] do
    put "confirmar", on: :member
  end
  
  resources :transfers, only: [:index]
  
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'password_reset/new'

  get 'password_reset/edit'
  
  get 'sales', to: "orders#sales"
  get 'purchases', to: "orders#purchases"
  get 'seller', to: "listings#seller"
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'bank_accounts/monitoreo', to: 'bank_accounts#monitoreo'
  get 'orders/monitoreo'
  get 'transfers/monitoreo'
  
end

app/models/order.rb
class Order < ApplicationRecord
  validates :seller_id, :buyer_id, :listing_id, presence: true  
  
  belongs_to :listing
  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"
  
  has_one :delivery_address, as: :addressable, class_name: "Address", dependent: :destroy
  
  accepts_nested_attributes_for :delivery_address

  enum status: [ :ordered, :shipped, :delivered, :rated ]
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :index, :sales, :purchases]
  before_action :complete_user, only: [:new, :create]
  before_action :correct_user,   only: [:new, :create]
  before_action :admin_user, only: [:monitoreo]
  def sales
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
  end
  
  def purchases
    @orders = Order.all.where(buyer: current_user).order("created_at DESC")
  end

  def show
    @listing = Listing.find(params[:id])
    @order 
  end
  
  def monitoreo
    @orders = Order.all.order("status")
  end
  

  def new
    @listing = Listing.find(params[:listing_id])
    @order = @listing.orders.build
    @order.build_delivery_address
  end

  def create
    
    @listing = Listing.find(params[:listing_id])
    @order = @listing.orders.build(order_params)
    @seller = @listing.user
    @order.seller_id = @seller.id
    @order.buyer_id = current_user.id
    
    
    Stripe.api_key = ENV["stripe_api_key"]
    token = params[:stripeToken]

    begin
      charge = Stripe::Charge.create(
        :amount => (@listing.price * 100).floor,
        :currency => "dop",
        :card => token
        )
      flash[:success] = "Thanks for ordering!"
    rescue Stripe::CardError => e
      flash[:danger] = e.message
    end
    
    if @order.save
      @seller.update_attributes(balance: @seller.balance + @listing.price)
      redirect_to listings_path
    else
      render 'new'
    end
  end
  
  def ship
    @order = Order.find(params[:id])
    if @order.update_attributes(status: params[:status])
      flash[:success] = "Producto enviado"
    else
      flash[:danger] = "Algo pasó intente de nuevo"
    end
    redirect_to ordenes_monitoreo_path
  end
  
  
  
  
  private
  
  def order_params
    params.require(:order).permit(delivery_address_attributes: [:city, :sector,
                                                                :line_1, :line_2])
  end
  
  
  def correct_user
      @listing = Listing.find(params[:listing_id])
      if current_user?(@listing.user)
        redirect_to(root_url)
        flash[:danger] = "Sorry, you can't buy your own product"
      end
  end
  
end

  

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="row">
  
  
  <div class="col-md-4">
    <div class="thumbnail">
      <%= image_tag @listing.picture.url %>
    </div>
      <h3><%= @listing.name %></h3>
      <h4><%= number_to_currency(@listing.price) %></h4>
  </div>
  
  <div class="col-md-6 col-md-offset-1">
    
    <%= form_for([@listing, @order]) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div id="stripe_error" class="alert alert-danger" style="display:none">
        <noscript>
          JavaScript is not enabled and is required for this form. First enable it in your web browser settings.
        </noscript>
    </div>
    
      <div class = "row">
        <div class = "col-md-12">
            <%= f.fields_for :delivery_address do |u| %>
        
                <%= u.label :city %>
                <%= u.text_field :city, class: 'form-control' %>
                
                <%= u.label :sector %>
                <%= u.text_field :sector, class: 'form-control' %>
                
                <%= u.label :line_1 %>
                <%= u.text_field :line_1, class: 'form-control' %>
                
                <%= u.label :line_2 %>
                <%= u.text_field :line_2, class: 'form-control' %>
                
            <% end %>
            
          </div>
      </div>
      
      <div class = "row">      
          <div class = "col-md-8">
            <%= label_tag :card_number, "Credit Card Number" %>
            <%= text_field_tag :card_number, nil, { :name => nil, :'data-stripe' => "number",
                                                    class: "form-control" } %>  
          </div>
          
          <div class = "col-md-4">
            <%= label_tag :card_code, "CVC" %>
            <%= text_field_tag :card_code, nil, { :name => nil, :'data-stripe' => "cvc",
                                                    class: "form-control" } %>
          </div>
      </div>
      
      <div class = "form-group">
        <%= label_tag nil, "Fecha de Caducidad" %>
        <div class = "row">      
          <div class = "col-md-6">
              <%= select_month nil, { use_two_digit_numbers: true }, { :name => nil, :'data-stripe' => "exp-month",
                                                                      class: "form-control" } %>
          </div>
          
          <div class="col-md-6">
            
            <%= select_year nil, { start_year: Date.today.year,
                                    end_year: Date.today.year+10 },
                                { :name => nil, :'data-stripe' => "exp-year", class: "form-control" } %>
          </div>
        </div>
      </div>
      
      <div class = "row">
        <div class = "col-md-4">
          <%= f.submit "submit", class: "btn btn-primary" %>

          <% end %>
          </div>
      </div>
  </div>
  
  
</div>

app/views/orders/monitoreo.html.erb
<div class="center">
  <h2>Ordenes</h2>
</div>

<table class="table table-striped">
  <tr>
    <th class="center">Producto</th>
    <th class="center">Precio</th>
    <th class="center">Vendedor</th>
    <th class="center">Comprador</th>
    <th class="center">Fecha de compra</th>
    <th class="center">Estatus</th>
  </tr>

  <% @orders.each do |order| %>
    <tr>
      <td class="center"><p><%= image_tag order.listing.picture.url(:thumb) %></p>
      <%= order.listing.name %></td>
      <td class="center"><%= number_to_currency(order.listing.price) %></td>
      <td class="center">
        <p><%= order.seller.name %></p>
        <p><%= order.listing.pickup_address.city %></p>
        <p><%= order.listing.pickup_address.sector %></p>
        <p><%= order.listing.pickup_address.line_1 %></p>
        <p><%= order.listing.pickup_address.line_2 if order.delivery_address.line_2? %></p>
      </td>
      <td class="center">
        <p><%= order.buyer.name %></p>
        <p><%= order.delivery_address.city %></p>
        <p><%= order.delivery_address.sector %></p>
        <p><%= order.delivery_address.line_1 %></p>
        <p><%= order.delivery_address.line_2 if order.delivery_address.line_2? %></p>
      </td>
      <td class="center"><%= order.created_at.strftime("%-d/ %m/ %Y") %></td>
      <td>
        <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            <% if order.ordered? %>
            En espera
            <% elsif order.shipped? %>
            Buscado
            <% elsif order.delivered? %>
            Enviado
            <% elsif order.rated? %>
            Evaluado
            <% end %>
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
          <% if order.ordered? %>
            <li><%= link_to "Buscado", ship_order_path(order, :status => "shipped"), method: :put, class: "btn btn-link" %></li>
            <% elsif order.shipped? %>
            <li><%= link_to "Enviado", ship_order_path(order, :status => "delivered"), method: :put, class: "btn btn-link" %></li>
            <% elsif order.delivered? %>
            <li><%= link_to "Evaluado", ship_order_path(order, :status => "rated"), method: :put, class: "btn btn-link" %></li>
            </ul>
        </div>
          <%end%>
      </td>
    </tr>
  <% end %>
</table>

app/views/orders/new.html.erb
<%= render 'orders/form' %>

<%= link_to 'Back', listing_orders_path(@listing) %>

app/views/orders/purchases.html.erb
<div class="center">
  <h2>Your Sales History</h2>
</div>

<table class="table table-striped">
  <tr>
    <th class="center">Image</th>
    <th class="center">Item</th>
    <th class="center">Description</th>
    <th class="center">Price</th>
    <th class="center">Seller</th>
    <th class="center">Date sold</th>
    <th class="center">Action</th>
  </tr>

  <% @orders.each do |order| %>
    <tr>
      <td class="center"><%= image_tag order.listing.picture.url(:thumb) %></td>
      <td class="center"><%= order.listing.name %></td>
      <td class="center"><%= order.listing.description %></td>
      <td class="center"><%= number_to_currency(order.listing.price) %></td>
      <td class="center"><%= order.seller.name %></td>
      <td class="center"><%= order.created_at.strftime("%m %-d, %Y") %></td>
      <td>
        <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "View", "#", class: "btn btn-link" %></li>
            <li><%= link_to "Edit", "#", class: "btn btn-link" %></li>
            <li><%= link_to 'Destroy', "#", class: "btn btn-link" %></li>
          </ul>
        </div>
      </td>
    </tr>
  <% end %>
</table>

app/views/orders/sales.html.erb
<div class="center">
  <h2>Historial de Ventas</h2>
</div>

<table class="table table-striped">
  <tr>
    <th class="center">Imagen</th>
    <th class="center">Producto</th>
    <th class="center">Descripcion</th>
    <th class="center">Precio</th>
    <th class="center">Comprador</th>
    <th class="center">Fecha de venta</th>
    <th class="center">Estatus</th>
  </tr>

  <% @orders.each do |order| %>
    <tr>
      <td class="center"><%= image_tag order.listing.picture.url(:thumb) %></td>
      <td class="center"><%= order.listing.name %></td>
      <td class="center"><%= order.listing.description %></td>
      <td class="center"><%= number_to_currency(order.listing.price) %></td>
      <td class="center"><%= order.buyer.name %></td>
      <td class="center"><%= order.created_at.strftime("%-d %m, %Y") %></td>
      <td>
          <% if order.shipped? %>
          <button type="button" class="btn btn-default">
            <%= order.status %>
          </button>
          <% else %>
            <%= link_to "Ya envie!", ship_order_path(order, :status => "shipped"), method: :put, class: "btn btn-default" %>
          <%end%>
      </td>
    </tr>
  <% end %>
</table>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>