config/routes.rb
Rails.application.routes.draw do
  
  

  get 'reviews/new'

  get 'reviews/create'

  get 'reviews/update'

  root 'static_pages#home'

  resources :listings do
    collection do
      get 'search'
    end
    resources :orders, only: [:show, :new, :create]
    resources :comments, only: [:create, :destroy]
  end
  
  resources :orders, only: [] do
    put "ship", on: :member
  end
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]  
  resources :bank_accounts, only: [:new, :create, :index, :destroy] do
    resources :transfers, only: [:new, :create]
  end
  
  resources :bank_accounts, only: [] do
    put "confirmar", on: :member
  end
  
  resources :transfers, only: [] do
    put "confirmar", on: :member
  end
  
  resources :transfers, only: [:index]
  
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'password_reset/new'

  get 'password_reset/edit'
  
  get 'sales', to: "orders#sales"
  get 'purchases', to: "orders#purchases"
  get 'seller', to: "listings#seller"
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'bank_accounts/monitoreo', to: 'bank_accounts#monitoreo'
  get 'orders/monitoreo'
  get 'transfers/monitoreo'
  
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :user
  enum status: [:revision ,:confirmado, :rechazado]
  has_many :transfers
  validates :user_id, :banco, :cuenta, :titular, presence: true
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  
  before_action :logged_in_user, olny: [:index, :new, :create, :destroy]
  before_action :admin_user, only: [:monitoreo, :confirmar]
  
  def index
    @bank_account= BankAccount.where(user: current_user)
  end


  def new
    @bank_account = current_user.bank_accounts.build
    @bancos = ["Popular", "Banreservas", "Progreso", "BHD Leon", "Scotiabank", "Santa Cruz",
                    "Banco Ademi"]
  end
  
  
  def monitoreo
    @bank_accounts = BankAccount.all
  end
  
  def confirmar 
   @bank_account = BankAccount.find(params[:id])
    if @bank_account.update_attributes(status: params[:status])
      flash[:success] = "Cambios guardados"
    else
      flash[:danger] = "Algo pasó intente de nuevo"
    end
   redirect_to bank_accounts_monitoreo_path
  end
  
  def create
    @bank_account = current_user.bank_accounts.build(bank_params)
    
    if @bank_account.save
      flash[:success] = "Solicitud recibida! Te avisaremos cuando confirmemos la Cuentas"
      redirect_to action: "index"
    else
      render 'new'
    end
  end
  
  def destroy
    BankAccount.find(params[:id]).destroy
    flash[:success] = "Cuenta eliminada"
    redirect_to bank_accounts_url
  end

  #def edit
  #  @bank_account = BankAccount.find(params[:id])
  #end

  #def update
  #end
  
  private
  
  def bank_params
    params.require(:bank_account).permit(:titular, :banco, :cuenta)
  end
  
  
end

app/helpers/bank_accounts_helper.rb
module BankAccountsHelper
end

app/views/bank_accounts/_form.html.erb
<%= form_for(@bank_account) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
<div class = "row">
    <div class = "col-md-6 col-md-offset-3">

        <%= f.label :titular %>
        <%= f.text_field :titular, class: 'form-control' %>
        
        <%= f.label :banco %>
        <%= f.select :banco, @bancos, {} , class: 'form-control' %>
    
        <%= f.label :cuenta %>
        <%= f.text_field :cuenta, class: 'form-control' %>
        
    
        <%= f.submit "submit", class: "btn btn-primary" %>

    </div>
 </div>
<% end %>

app/views/bank_accounts/index.html.erb
<h1>Cuentas de banco</h1>

<table class="table table-hover">
  <tr>
    <th class="center">Banco</th>
    <th class="center">Cuenta</th>
    <th class="center">Titular</th>
    <th class="center">Acciones</th>
  </tr>

  <% @bank_account.each do |t| %>
    <tr class="<%="danger" if t.revision? %>">
      <td class="center"><%= t.banco %></td>
      <td class="center"><%= t.cuenta %></td>
      <td class="center"><%= t.titular %></td>
      <td class="center">
        <% if t.revision? %>
          <p>Cuenta en Revision</p>
        <% else %>
          <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
              transaccion <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Transferir pagos", new_bank_account_transfer_path(t), class: "btn btn-link" %></li>
              <li><%= link_to "Eliminar cuenta", t, method: :delete, data: {confirm: "Seguro?"}, class: "btn btn-link" %></li>
            </ul>
          </div>
        <% end %>
      </td>
  <% end %>
</table>

<%= link_to "dldl", bank_accounts_monitoreo_path %>

<div class="row">
  <div class="col-md-9">
    <%= link_to "Añadir cuenta de banco", new_bank_account_path, class: "btn btn-primary" %>
  </div>  
  
  <div class="col-md-3">
    <%= link_to "Historial de Transferencias", transfers_path %>
  </div>
  
</div>

app/views/bank_accounts/monitoreo.html.erb
<div class="center">
  <h2>Cuentas de banco</h2>
</div>

<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Usuario</th>
    <th class="center">Banco</th>
    <th class="center">Cuenta</th>
    <th class="center">Titular</th>
    <th class="center">Fecha solicitada</th>
    <th class="center">Estatus</th>
  </tr>

  <% @bank_accounts.each do |t| %>
    <tr>
      <td class="center"><%= t.user.username %></td>
      <td class="center"><%= t.banco %></td>
      <td class="center"><%= t.cuenta %></td>
      <td class="center"><%= t.titular %></td>
      <td class="center"><%= t.created_at.strftime("%-d/ %m/ %Y") %></td>
      <td class="center">
        <% if t.revision? %>
        <div class="btn-group">
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
             <%= t.status%> <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Aprobado", confirmar_bank_account_path(t, :status => "confirmado"), method: :put, data: {confirm: "cambiar estatus a confirmado?"}, class: "btn btn-link" %></li>
            <li><%= link_to "Rechazado", confirmar_bank_account_path(t, :status => "rechazado"), method: :put, data: {confirm: "cambiar estatus a rechazado?"}, class: "btn btn-link" %></li>
          </ul>
        </div>
        <% else %>
          <%= t.status %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/bank_accounts/new.html.erb
<%= render 'form' %>