config/routes.rb
Rails.application.routes.draw do
  
  

  get 'reviews/new'

  get 'reviews/create'

  get 'reviews/update'

  root 'static_pages#home'

  resources :listings do
    collection do
      get 'search'
    end
    resources :orders, only: [:show, :new, :create]
    resources :comments, only: [:create, :destroy]
  end
  
  resources :orders, only: [] do
    put "ship", on: :member
  end
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]  
  resources :bank_accounts, only: [:new, :create, :index, :destroy] do
    resources :transfers, only: [:new, :create]
  end
  
  resources :bank_accounts, only: [] do
    put "confirmar", on: :member
  end
  
  resources :transfers, only: [] do
    put "confirmar", on: :member
  end
  
  resources :transfers, only: [:index]
  
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'password_reset/new'

  get 'password_reset/edit'
  
  get 'sales', to: "orders#sales"
  get 'purchases', to: "orders#purchases"
  get 'seller', to: "listings#seller"
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'bank_accounts/monitoreo', to: 'bank_accounts#monitoreo'
  get 'orders/monitoreo'
  get 'transfers/monitoreo'
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
   info@korotos.com.do
  </small>
  <nav>
    <ul>
      <li><%= link_to "Nosotros",   about_path %></li>
      <li><%= link_to "Contacto", contact_path %></li>
      <li><a href="#">Noticias</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
<head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/" %>
    <%= render 'layouts/shim' %>
    <%= tag :meta, :name => "stripe-key", :content => ENV["stripe_publishable_key"] %>
    
    
  </head>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-default">
      <div class="container">
        <%= link_to "Korotos", root_path, id: "logo" %>
        <nav>
          
          
          
          <ul class="nav navbar-nav navbar-right">
            
            
            <li><%= link_to "Vender",   new_listing_path %></li>
            <li><%= link_to "Ayuda",   help_path %></li>
            <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Categorias <b class="caret"></b>
                  </a>
                <ul class="dropdown-menu">
                  <li><%=link_to "Todo", listings_path %></li>
                  <li class="divider"></li>
                  <% Category.all.each do |c| %>
                  <li class="dropdown-header"><%= c.name %></li>
                  <% c.subcategories.each do |s| %>
                    <li><%= link_to s.name, listings_path(subcategory: s.name) %></li>
                  <% end %> 
                  <li class="divider"></li>
                  <% end %>
                  
                </ul>
            </li>
            <% if logged_in? %>
            <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Cuenta <b class="caret"></b>
                  </a>
                <ul class="dropdown-menu">
                    <li><%= link_to "Perfil", current_user %></li>
                    <li><%= link_to "Configuracion", edit_user_path(current_user) %></li>
                    <li><!--%= link_to "Bancos y Transferencias", bank_accounts_url %--></li>
                    <li><%= link_to "Mi listado", seller_path %></li>
                    <li><!--%= link_to "Ventas", sales_path %--></li>
                    <li><!--%= link_to "Compras", purchases_path %--></li>
                    <li class="divider"></li>
                    <li>
                        <%= link_to "Cerrar Sesion", logout_path, method: "delete" %>
                    </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
      </ul>
      <%= form_tag search_listings_path, method: :get, class: "navbar-form navbar-right" do %>
           
              <%= text_field_tag :search, params[:search], placeholder: "buscar", class: "form-control", style: "margin-bottom: 0" %>
              <%= button_tag(type: "submit", class: "btn btn-default") do %>
                  <span class="glyphicon glyphicon-search"></span>
              <% end %>
         
          <% end %>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/_sidebar.html.erb
<div class="col-md-3 sidebar center">  
  
    <%= link_to gravatar_for(current_user, size: 100), current_user %>
    <h1><%= current_user.name %></h1>
    <!--p><b>Balance:</b> <!--%= number_to_currency(current_user.balance) %--><!--/p-->
    <%= link_to "ver mi perfil", current_user %>
    <hr>
    
</div>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  
  <body>
    <%= render 'layouts/header' %>
    
       
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
    
          <%= render 'layouts/footer' %>

  </body>
</html>